
export const ALL_SKILLS = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "Dart",
  "Kotlin",
  "Swift",
  "PHP",
  "Go",
  "Ruby",
  "Rust",
  "SQL",
  "NoSQL",
  "React.js",
  "Next.js",
  "Angular",
  "Vue.js",
  "Svelte",
  "Node.js",
  "Express.js",
  "Flutter",
  "Django",
  "Flask",
  "Spring Boot",
  "Laravel",
  "CodeIgniter",
  "ASP.NET",
  "Android SDK",
  "iOS SDK",
  "React Native",
  "Firebase",
  "Firestore",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Supabase",
  "Redis",
  "Prisma ORM",
  "GraphQL",
  "AWS",
  "Google Cloud",
  "Azure",
  "Docker",
  "Kubernetes",
  "Vercel",
  "Netlify",
  "GitHub Actions",
  "Jenkins",
  "GitLab CI/CD",
  "Firebase Hosting",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Postman",
  "Thunder Client",
  "Swagger",
  "OpenAPI",
  "VS Code",
  "IntelliJ",
  "Android Studio",
  "Linux",
  "WSL",
  "Command Line",
  "Manual Testing",
  "Automation Testing",
  "Functional Testing",
  "Regression Testing",
  "Performance Testing",
  "Load Testing",
  "Stress Testing",
  "Smoke Testing",
  "Sanity Testing",
  "Security Testing",
  "Selenium",
  "Cypress",
  "Playwright",
  "Appium",
  "TestNG",
  "JUnit",
  "PyTest",
  "Unittest",
  "Puppeteer",
  "Jira",
  "Trello",
  "Asana",
  "TestRail",
  "QTest",
  "Bugzilla",
  "Zephyr",
  "SoapUI",
  "REST Assured",
  "Allure Reports",
  "Extent Reports",
  "TestNG Reports",
  "BrowserStack",
  "LambdaTest",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "Canva",
  "Design Systems",
  "Wireframing",
  "Prototyping",
  "User Journey Mapping",
  "Accessibility Design",
  "Responsive Design",
  "Low-Fidelity Wireframes",
  "High-Fidelity Wireframes",
  "UI Kits",
  "Design Tokens",
  "Developer Handoff",
  "Zeplin",
  "InVision",
  "LottieFiles",
  "Maze",
  "Lookback",
  "FigJam",
  "Communication",
  "Collaboration",
  "Problem Solving",
  "Time Management",
  "Attention to Detail",
  "Agile",
  "Scrum",
  "Documentation"
];
